<?php $item = $this->item; /** @var $item \DevCtrl\Domain\Item\Item */ ?>
<?php echo $this->pageTitle('Add relation to item', $item->getTitle()); ?>
<div class="btn-group">
    <a class="btn btn-primary" href="<?php echo $this->url('default/id', array(
            'controller' => 'item',
            'action' => 'assign-user',
            'id' => $item->getId()
        )); ?>">
        Assign new user
    </a>
</div>
<?php //echo $this->partial('dev-ctrl/user/partial/widget.phtml', array('user' => $item->getCreatedBy())); ?>
<p></p>
<div class="">
    <table class="table table-striped">
        <tr>
            <th>title</th>
            <th>description</th>
            <th>state</th>
            <th>actions</th>
        </tr>
        <?php foreach ($items as $i): ?>
        <tr>
            <td><?php echo $i->getTitle(); ?></td>
            <td><?php echo $i->getDescription(); ?></td>
            <td><?php if ($i->getItemType()->supportsStates()) echo $i->getState()->getLabel(); ?></td>
            <td>
                <?php echo $this->ctrlButton('link', array('value' => 'add relation',
                'href' => $this->url('default/id/query', array(
                    'controller' => 'item',
                    'action' => 'add-relation',
                    'id' => $item->getId(),
                    'related-item' => $i->getId(),
                    'type' => $type,
                ))), 'primary') ?>
            </td>
        </tr>
        <?php endforeach; ?>
    </table>
</div>