<?php use DevCtrl\Domain\Item\Property\Property; ?>
<?php $itemType = $this->itemType; /** @var $itemType \DevCtrl\Domain\Item\Type\Type */ ?>
<?php echo $this->pageTitle('New item'); ?>

<form class="form-horizontal ctrljs-validate" method="post" id="form-item-create" action="<?php echo $this->url('item_create', array(
    'controller' => 'item',
    'action' => 'create',
    'item-type' => $itemType->getId(),
)); ?>">
    <fieldset class="part-1">
        <legend>Configure your item</legend>
        <?php
        foreach ($form->getElements() as $e) {
            echo $this->ctrlFormInput($e);
        }

        echo $this->ctrlFormActions(array(
            $this->ctrlButton('submit', array('value' => 'save'), 'primary'),
            $this->ctrlButton('link', array('value' => 'cancel', 'href' => $form->getReturnUrl()))
        ));
        ?>
    </fieldset>
</form>

<script type="text/javascript">

</script>