<?php use DevCtrl\Domain\Item\Item; ?>
<?php $item = $this->item; /** @var $item Item */ ?>

<?php echo $this->pageTitle('Item detail', $item->getItemType()->getName()); ?>

<?php $this->itemTab = 'detail'; ?>
<?php echo $this->render('dev-ctrl/item/partial/item-tabs.phtml'); ?>

<table class="table table-bordered">
    <tr>
        <th width="200">title</th>
        <td><?php echo $item->getTitle(); ?></td>
        <th width="200">state</th>
        <td>
            <?php if ($item->getItemType()->hasStates()): ?>
            <span class="label label-<?php
                echo ($item->getState()->getNativeState() == $item->getState()->getNativeStates(\DevCtrl\Domain\Item\State\State::STATE_CLOSED)) ?
                    'inverse': 'success'; ?>"><?php echo $item->getState()->getLabel() ?></span>
            <?php endif; ?>
        </td>
    </tr>
    <?php if ($item->getItemType()->supportsTiming()): ?>
    <tr>
        <th>timing</th>
        <td><?php echo $item->getTimeCounter()->getEstimated(); ?> / <?php echo $item->getTimeCounter()->getExecuted(); ?></td>
        <th>created by</th>
        <td>
            <a href="#"><?php echo $item->getCreatedBy()->getUsername(); ?></a>
        </td>
    </tr>
    <?php endif; ?>
    <tr>
        <th>description</th>
        <td colspan="3"><?php echo $item->getDescription(); ?></td>
    </tr>
    <?php foreach($item->getItemProperties() as $ip): ?>
    <tr>
        <th><?php echo $ip->getTypeProperty()->getProperty()->getName(); ?></th>
        <td colspan="3"><?php echo $ip->getDisplayValue(); ?></td>
    </tr>
    <?php endforeach; ?>
</table>

<?php echo $this->pageTitle('Last comments', null, array('level' => 3)); ?>