<?php use DevCtrl\Domain\Item\Item; ?>
<?php $item = $this->item; /** @var $item Item */ ?>

<?php echo $this->pageTitle('Item detail', $item->getItemType()->getName()); ?>

<?php $this->itemTab = 'detail'; ?>
<?php echo $this->render('dev-ctrl/item/partial/item-tabs.phtml'); ?>

<table class="table table-bordered">
    <tr>
        <th width="200">title</th>
        <td colspan="3"><?php echo $item->getTitle(); ?></td>
    </tr>
    <tr>
        <th width="200">state</th>
        <td>
            <?php if ($item->getItemType()->supportsStates()): ?>
            <span class="label label-<?php
                echo ($item->getState()->getNativeState() == $item->getState()->getNativeStates(\DevCtrl\Domain\Item\State\State::STATE_CLOSED)) ?
                    'inverse': 'success'; ?>"><?php echo $item->getState()->getLabel() ?></span>
            <?php endif; ?>
        </td>
        <th>created by</th>
        <td>
            <a href="#"><?php echo $item->getCreatedBy()->getUsername(); ?></a>
        </td>
    </tr>
    <?php if ($item->getItemType()->supportsVersions()): ?>
    <tr>
        <th>version reported</th>
        <td><?php if ($item->getVersionReported()) echo $item->getVersionReported()->getVersion().' '.$item->getVersionReported()->getLabel(); ?></td>
        <th>version fixed</th>
        <td><?php if ($item->getVersionFixed()) echo $item->getVersionFixed()->getVersion().' '.$item->getVersionFixed()->getLabel(); ?></td>
    </tr>
    <?php endif; ?>
    <?php if ($item->getItemType()->supportsTiming()): ?>
    <tr>
        <th>timing</th>
        <td colspan="3"><span class="icon-time"></span> <?php echo $item->getTimeCounter()->getEstimated(); ?> / <?php echo $item->getTimeCounter()->getExecuted(); ?></td>
    </tr>
    <?php endif; ?>
    <tr>
        <th>description</th>
        <td colspan="3"><?php echo $item->getDescription(); ?></td>
    </tr>
    <?php foreach($item->getItemProperties() as $ip): ?>
    <tr>
        <th><?php echo $ip->getTypeProperty()->getProperty()->getName(); ?></th>
        <td colspan="3"><?php echo $ip->getDisplayValue(); ?></td>
    </tr>
    <?php endforeach; ?>
</table>


<?php echo $this->pageTitle('Related items', null, array('level' => 3)); ?>
<div class="btn-group">
    <a class="btn btn-primary btn-mini" href="<?php echo $this->url('default/id', array(
        'controller' => 'item',
        'action' => 'add-relation',
        'id' => $item->getId()
    )); ?>">
        Add new relation
    </a>
</div>

<p></p>
<?php if (count($item->getItemRelations())): ?>
<table class="table table-striped">
    <tr>
        <th>type</th>
        <th>id</th>
        <th>title</th>
    </tr>
    <?php foreach ($item->getItemRelations() as $ir): ?>
    <tr>
        <td><?php echo $ir->getType(); ?></td>
        <td><?php echo $ir->getItem()->getId(); ?></td>
        <td><?php echo $ir->getItem()->getTitle(); ?></td>
    </tr>
    <?php endforeach; ?>
</table>
<?php else: ?>
<p>No relations</p>
<?php endif; ?>

<p></p>
<?php echo $this->pageTitle('Last comments', null, array('level' => 3)); ?>
<div class="btn-group">
    <a class="btn btn-primary btn-mini" href="<?php echo $this->url('default/id', array(
        'controller' => 'item',
        'action' => 'add-relation',
        'id' => $item->getId()
    )); ?>">
        Add comment
    </a>
</div>
<p>No comments</p>