<?php
/** @var $this \Ctrl\View\PhpView
 * @var $item \DevCtrl\Domain\Item\Item
 * @var $form \Ctrl\Form\Form */
use DevCtrl\Domain\Item\Property\Property;
echo $this->pageTitle('Edit item', $item->getTitle());

$form->setLabel('Please make your changes');
echo $this->ctrlForm()->start($form);

foreach ($form->getElements() as $e) {
    echo $this->ctrlFormInput($e);
}

echo $this->ctrlFormActions(array(
    $this->ctrlButton('submit', array('value' => 'save'), 'primary'),
    $this->ctrlButton('link', array('value' => 'cancel', 'href' => $form->getReturnUrl()))
));

echo $this->ctrlForm()->end($form);