<?php $items = $this->items; /** @var $items \DevCtrl\Domain\Item\Item[] */ ?>
<?php $types = $this->itemTypes; /** @var $types \DevCtrl\Domain\Item\Type\Type[] */ ?>
<?php echo $this->pageTitle('Items'); ?>
<div class="btn-group">
    <a class="btn dropdown-toggle btn-primary" data-toggle="dropdown" href="#">
        New item
        <span class="caret"></span>
    </a>
    <ul class="dropdown-menu">
        <?php foreach ($types as $t): ?>
        <li><a href="<?php echo $this->url('item_create', array(
            'type' => $t->getId()
        )); ?>"><?php echo $t->getName(); ?></a></li>
        <?php endforeach; ?>
    </ul>
</div>
<p></p>
<div class="">
    <table class="table table-striped">
        <tr>
            <th>id</th>
            <th>name</th>
            <th>progress</th>
            <th>state</th>
            <th>actions</th>
        </tr>
        <?php foreach ($items as $i): ?>
        <tr>
            <td><?php echo $tp->getId(); ?></td>
            <td><?php echo $tp->getName(); ?></td>
            <td><?php echo $tp->getDescription(); ?></td>
            <td><?php echo $tp->supportsTiming() ?></td>
            <td><?php echo $tp->hasStates() ? $tp->getStates()->getName() : ''; ?></td>
            <td>
                <?php echo $this->ctrlButton('link', array('value' => 'detail',
                'href' => $this->url('default/id', array(
                    'controller' => 'item-type',
                    'action' => 'detail',
                    'id' => $tp->getId()
                ))), 'info') ?>
        </tr>
        <?php endforeach; ?>
    </table>
</div>