<?php $itemType = $this->itemType; /** @var $itemType \DevCtrl\Domain\Item\ItemType */ ?>
<?php foreach ($itemType->getItemTypeProperties() as $p): ?>
<div class="control-group">
    <label class="control-label"><?php echo $p->getProperty()->getName(); ?></label>
    <div class="controls">
        <input type="text"
               class="input-xxlarge <?php if ($p->getRequired()) echo 'required'; ?>"
               name="item-type-property[<?php echo $p->getProperty()->getId(); ?>]" />
    </div>
</div>
<?php endforeach; ?>