<?php $item = $this->item; /** @var $item \DevCtrl\Domain\Item\Item */ ?>
<?php echo $this->pageTitle('Related users', $item->getTitle()); ?>
<?php $this->itemTab = 'related-users'; ?>
<?php echo $this->render('dev-ctrl/item/partial/item-tabs.phtml'); ?>
<div class="btn-group">
    <a class="btn btn-primary" data-toggle="dropdown" href="#">
        Assign new user
    </a>
</div>
<?php echo $this->partial('dev-ctrl/user/partial/widget.phtml', array('user' => $item->getCreatedBy())); ?>
<p></p>
<?php echo $this->pageTitle('Assigned users', null, array('level' => 4)); ?>
<p></p>
<div class="">
    <table class="table table-striped">
        <tr>
            <th>id</th>
            <th>name</th>
            <th>progress</th>
            <th>state</th>
            <th>actions</th>
        </tr>
        <?php foreach ($items as $i): ?>
        <tr>
            <td><?php echo $i->getId(); ?></td>
            <td><?php echo $i->getTitle(); ?></td>
            <td><?php echo $i->getItemType()->supportsTiming() ?></td>
            <td><?php echo $i->getItemType()->hasStates() ? $i->getState()->getLabel() : ''; ?></td>
            <td>
                <?php echo $this->ctrlButton('link', array('value' => 'detail',
                'href' => $this->url('default/id', array(
                    'controller' => 'item',
                    'action' => 'detail',
                    'id' => $i->getId()
                ))), 'info') ?>
        </tr>
        <?php endforeach; ?>
    </table>
</div>
<p></p>
<?php echo $this->pageTitle('Creator', null, array('level' => 4)); ?>
<p></p>
<div class="">
    <table class="table table-striped">
        <tr>
            <th>id</th>
            <th>name</th>
            <th>progress</th>
            <th>state</th>
            <th>actions</th>
        </tr>
        <?php foreach ($items as $i): ?>
        <tr>
            <td><?php echo $i->getId(); ?></td>
            <td><?php echo $i->getTitle(); ?></td>
            <td><?php echo $i->getItemType()->supportsTiming() ?></td>
            <td><?php echo $i->getItemType()->hasStates() ? $i->getState()->getLabel() : ''; ?></td>
            <td>
                <?php echo $this->ctrlButton('link', array('value' => 'detail',
                'href' => $this->url('default/id', array(
                    'controller' => 'item',
                    'action' => 'detail',
                    'id' => $i->getId()
                ))), 'info') ?>
        </tr>
        <?php endforeach; ?>
    </table>
</div>

<p></p>
<?php echo $this->pageTitle('Followers', null, array('level' => 4)); ?>
<p></p>
<div class="">
    <table class="table table-striped">
        <tr>
            <th>id</th>
            <th>name</th>
            <th>progress</th>
            <th>state</th>
            <th>actions</th>
        </tr>
        <?php foreach ($items as $i): ?>
        <tr>
            <td><?php echo $i->getId(); ?></td>
            <td><?php echo $i->getTitle(); ?></td>
            <td><?php echo $i->getItemType()->supportsTiming() ?></td>
            <td><?php echo $i->getItemType()->hasStates() ? $i->getState()->getLabel() : ''; ?></td>
            <td>
                <?php echo $this->ctrlButton('link', array('value' => 'detail',
                'href' => $this->url('default/id', array(
                    'controller' => 'item',
                    'action' => 'detail',
                    'id' => $i->getId()
                ))), 'info') ?>
        </tr>
        <?php endforeach; ?>
    </table>
</div>