<ul class="nav nav-tabs">
    <li<?php if ($this->page == 'info') echo ' class="active"'; ?>><a href="<?php echo $this->url('default/id', array(
        'controller' => 'project',
        'action' => 'detail',
        'id' => $this->project->getId()
    )); ?>">Info</a></li>
    <li<?php if ($this->page == 'backlog') echo ' class="active"'; ?>><a href="<?php echo $this->url('default/id', array(
        'controller' => 'project',
        'action' => 'backlog',
        'id' => $this->project->getId()
    )); ?>">Backlog  <span class="label label-info"><?php echo count($this->project->getBacklog()); ?></span></a></li>
    <li<?php if ($this->page == 'milestones') echo ' class="active"'; ?>><a href="#">Milestones  <span class="label">0<?php //echo count($this->item->getAssignedUsers()); ?></span></a></li>
    <li<?php if ($this->page == 'versions') echo ' class="active"'; ?>><a href="<?php echo $this->url('default/id', array(
        'controller' => 'project',
        'action' => 'versions',
        'id' => $this->project->getId()
    )); ?>">Versions  <span class="label label-info"><?php echo count($this->project->getVersionList()); ?></span></a></li>
</ul>