<div class="page-header"><h1><?php echo $this->property->getName(); ?></h1></div>

<form class="form-horizontal" method="post" action="<?php echo $this->url('default/id', array(
    'controller' => 'property',
    'action' => 'add-value',
    'id' => $this->property->getId(),
)); ?>">
    <fieldset>
        <legend>Add a possible value</legend>
        <div class="control-group">
            <label class="control-label">value</label>
            <div class="controls">
                <input type="text" class="input-xxlarge required" name="value" />
            </div>
        </div>
        <div class="form-actions">
            <input type="submit" class="btn btn-primary" value="Add" />
            <a class="btn" href="<?php echo $this->url('default/id', array(
                'controller' => 'property',
                'action' => 'detail',
                'id' => $this->property->getId(),
            )); ?>">cancel</a>
        </div>
    </fieldset>
</form>