<ul class="nav nav-tabs">
    <li<?php if ($this->page == 'info') echo ' class="active"'; ?>><a href="<?php echo $this->url('default/id', array(
        'controller' => 'item-type',
        'action' => 'detail',
        'id' => $this->itemType->getId()
    )); ?>">Info</a></li>
    <?php if ($this->itemType->getHasState()): ?>
    <li<?php if ($this->page == 'states') echo ' class="active"'; ?>><a href="<?php echo $this->url('default/id', array(
        'controller' => 'item-type',
        'action' => 'states',
        'id' => $this->itemType->getId()
    )); ?>">States</a></li>
    <?php endif; ?>
</ul>