<?php /** @var $this \Ctrl\View\PhpView */ ?>
<?php /** @var $milestone \DevCtrl\Domain\Project\Milestone */ ?>
<?php echo $this->pageTitle('Project', $milestone->getProject()->getName()); ?>
<?php $this->page = 'milestones'; ?>
<?php $this->project = $milestone->getProject(); ?>
<?php echo $this->render('dev-ctrl/project/partial/project-tabs.phtml'); ?>

<div class="btn-group" style="float: right;">
    <?php echo $this->ctrlButton('link', array('value' => 'Add item',
    'href' => $this->url('default/id', array(
        'controller' => 'milestone',
        'action' => 'add-item',
        'id' => $milestone->getId(),
    ))), 'primary') ?>
    <a class="btn" href="#">edit</a>
</div>
<?php echo $this->pageTitle('Milestone', $milestone->getLabel(), array('level' => 1)); ?>
<p class="well well-small" style="display: inline-block; max-width: 75%"><?php echo nl2br($milestone->getDescription()); ?></p>
<?php echo $this->pageTitle('Overview', null, array('level' => 3)); ?>
<p></p>
<div class="row-fluid well" style="padding-right: 0; padding-left: 0;">
    <div class="row-fluid">
        <div class="span2" style="text-align: center">
            <?php $percentageCompleted = $milestone->getProgress(); ?>
                <button class="btn"><canvas class="ctrljs-3stage-gauge" guage-value="<?php echo $percentageCompleted; ?>" width="60" height="60"></canvas></button>
        </div>
        <div class="span10" style="text-align: left">
            <div class="row-fluid">
                <div class="span2" style="text-align: right">
                    <strong>name: </strong>
                </div>
                <div class="span4">
                    <a href="<?php echo $this->url('default/id', array(
                        'controller' => 'project',
                        'action' => 'detail',
                        'id' => $milestone->getId(),
                    ));?>"><?php echo $milestone->getLabel(); ?></a>
                </div>
                <div class="span2" style="text-align: right">
                    <strong>status: </strong>
                </div>
                <div class="span4">
                    <?php if ($percentageCompleted < 100): ?>
                    <span class="label label-success">healthy</span>
                    <?php elseif ($percentageCompleted < 130): ?>
                    <span class="label label-warning">warning</span>
                    <?php else: ?>
                    <span class="label label-important">problem</span>
                    <?php endif; ?>
                </div>
            </div>
            <div class="row-fluid">
                <div class="span2" style="text-align: right">
                    <strong>current version: </strong>
                </div>
                <div class="span4">
                    <?php echo $milestone->getResultingVersion()->getVersion().' '.$milestone->getResultingVersion()->getLabel(); ?>
                </div>
                <div class="span2" style="text-align: right">
                    <strong>item count: </strong>
                </div>
                <div class="span4">
                    <?php echo count($milestone->getBacklog()); ?>
                </div>
            </div>
            <div class="row-fluid">
                <div class="span2" style="text-align: right">
                    <strong>people involved: </strong>
                </div>
                <div class="span4">
                    4
                </div>
                <div class="span2" style="text-align: right">
                    <strong>last activity: </strong>
                </div>
                <div class="span4">
                    today
                </div>
            </div>
        </div>
    </div>
</div>

<?php if (count($milestone->getBacklog())): ?>
    <?php echo $this->pageTitle('Items assigned to me', null, array('level' => 3)); ?>
    <p></p>
    <?php foreach ($userItems as $i): ?>
    <?php echo $this->partial('dev-ctrl/item-widget-row', array('item' => $i)); ?>
    <?php endforeach; ?>

    <?php echo $this->pageTitle('Last updated items', null, array('level' => 3)); ?>
    <p></p>
    <?php foreach ($lastUpdatedItems as $i): ?>
    <?php echo $this->partial('dev-ctrl/item-widget-row', array('item' => $i)); ?>
    <?php endforeach; ?>
<?php endif; ?>