<?php /** @var $this \Ctrl\View\PhpView */ ?>
<?php echo $this->pageTitle('Milestones', $project->getName()); ?>
<?php $this->page = 'milestones'; ?>
<?php echo $this->render('dev-ctrl/project/partial/project-tabs.phtml'); ?>
<p></p>
<div class="btn-group">
    <?php echo $this->ctrlButton('link', array('value' => 'Add new project',
    'href' => $this->url('default', array(
        'controller' => 'project',
        'action' => 'create',
    ))), 'primary') ?>
</div>
<p></p>
<div class="">
    <table class="table table-striped">
        <tr>
            <th>name</th>
            <th>description</th>
            <th>actions</th>
        </tr>
        <?php foreach ($project->getMilestones() as $ms): ?>
        <tr>
            <td><?php echo $ms->getLabel(); ?></td>
            <td><?php echo $ms->getDescription(); ?></td>
            <td><a class="btn btn-info" href="<?php echo $this->url('default/id', array(
                'controller' => 'milstone',
                'action' => 'detail',
                'id' => $ms->getId()
            )); ?>">detail</a></td>
        </tr>
        <?php endforeach; ?>
    </table>
</div>