<div class="page-header"><h1><?php echo $this->project->getName(); ?></h1></div>

<form class="form-horizontal" method="post" action="<?php echo $this->url('default/id', array(
    'controller' => 'project',
    'action' => 'add-user',
    'id' => $this->project->getId(),
)); ?>">
    <fieldset>
        <legend>Add a user to the project</legend>
        <div class="control-group">
            <label class="control-label">users</label>
            <div class="controls">
                <select class="input-xxlarge" name="user" size="10">
                    <?php foreach ($this->users as $u): ?>
                        <option value="<?php echo $u->getId(); ?>"><?php echo $u->getAuthUser()->getUsername(); ?></option>
                    <?php endforeach; ?>
                </select>
                <p class="help-block">Only users who are not already linked to this project are shown</p>
            </div>
        </div>
        <div class="control-group">
            <label class="control-label">level</label>
            <div class="controls">
                <select class="input-xlarge" name="level">
                    <option>viewer</option>
                    <option>reporter</option>
                    <option>developer</option>
                    <option>admin</option>
                </select>
            </div>
        </div>
        <div class="form-actions">
            <input type="submit" class="btn btn-primary" value="Add" />
            <a class="btn" href="<?php echo $this->url('default/id', array(
                'controller' => 'project',
                'action' => 'users',
                'id' => $this->project->getId(),
            )); ?>">cancel</a>
        </div>
    </fieldset>
</form>