<?php /** @var $this \Ctrl\View\PhpView */ ?>
<?php $project = $this->project     /** @var $project   \DevCtrl\Domain\Project\Project */ ?>
<?php $types = $this->itemTypes;    /** @var $types     \DevCtrl\Domain\Item\Type\Type[] */ ?>
<?php $backlog = $this->backlog;   /** @var $backlog   \DevCtrl\Domain\Item\Item[] */ ?>
<?php echo $this->pageTitle('Project', $this->project->getName()); ?>

<?php $this->page = 'backlog'; ?>
<?php echo $this->render('dev-ctrl/project/partial/project-tabs.phtml'); ?>

<div class="btn-group">
    <a class="btn dropdown-toggle btn-primary" data-toggle="dropdown" href="#">
        New item
        <span class="caret"></span>
    </a>
    <ul class="dropdown-menu">
        <?php foreach ($types as $t): ?>
        <li><a href="<?php echo $this->url('item_create', array(
            'type' => $t->getId(),
            'project' => $project->getId()
        )); ?>"><?php echo $t->getName(); ?></a></li>
        <?php endforeach; ?>
    </ul>
</div>
<p></p>

<?php foreach ($backlog as $i): ?>
    <?php echo $this->partial('dev-ctrl/item-widget-row', array('item' => $i)); ?>
<?php endforeach; ?>