<?php /** @var $this \Ctrl\View\PhpView */ ?>
<?php $project = $this->project     /** @var $project   \DevCtrl\Domain\Project */ ?>
<?php $types = $this->itemTypes;    /** @var $types     \DevCtrl\Domain\Item\Type\Type[] */ ?>
<?php echo $this->pageTitle('Project', $this->project->getName()); ?>

<?php $this->page = 'backlog'; ?>
<?php echo $this->render('dev-ctrl/project/partial/project-tabs.phtml'); ?>

<div class="btn-group">
    <a class="btn dropdown-toggle btn-primary" data-toggle="dropdown" href="#">
        New item
        <span class="caret"></span>
    </a>
    <ul class="dropdown-menu">
        <?php foreach ($types as $t): ?>
        <li><a href="<?php echo $this->url('item_create', array(
            'type' => $t->getId(),
            'project' => $project->getId()
        )); ?>"><?php echo $t->getName(); ?></a></li>
        <?php endforeach; ?>
    </ul>
</div>
<p></p>
<div class="">
    <table class="table table-striped">
        <tr>
            <th>id</th>
            <th>title</th>
            <th>description</th>
            <th>actions</th>
        </tr>
        <?php foreach ($project->getBacklog() as $i): ?>
        <tr>
            <td><?php echo $i->getId(); ?></td>
            <td><?php echo $i->getTitle(); ?></td>
            <td><?php echo $i->getDescription(); ?></td>
            <td><a class="btn btn-info" href="<?php echo $this->url('default/id', array(
                'controller' => 'item',
                'action' => 'detail',
                'id' => $i->getId()
            )); ?>">detail</a></td>
        </tr>
        <?php endforeach; ?>
    </table>
</div>