<?php /** @var $this \Ctrl\View\PhpView */ ?>
<?php /** @var $project \DevCtrl\Domain\Project */ ?>
<?php $project = $this->project ?>
<?php echo $this->pageTitle('Project', $this->project->getName()); ?>
<p><?php echo $project->getDescription(); ?></p>
<?php $this->page = 'info'; ?>
<?php echo $this->render('dev-ctrl/project/partial/project-tabs.phtml'); ?>

<div class="btn-group">
    <a class="btn" href="#">edit</a>
    <a class="btn btn-success disabled" href="#">follow</a>
    <a class="btn" href="#">close</a>
</div>
<p></p>

<div class="row-fluid alert alert<?php echo $percentageCompleted < 100 ? '-success': '-danger'; ?>">
    <div class="row-fluid">
        <div class="span2" style="text-align: center">
            <?php $percentageCompleted = $project->getProgress(); ?>
                <button class="btn"><canvas class="ctrljs-3stage-gauge" guage-value="<?php echo $percentageCompleted; ?>" width="60" height="60"></canvas></button>
        </div>
        <div class="span10" style="text-align: center">
            <div class="row-fluid">
                <div class="span2" style="text-align: center">
                    <strong>status: </strong>
                </div>
                <div class="span1" style="text-align: center">
                    <span class="label label-success">healthy</span><br />
                </div>
            </div>
            <div class="row-fluid">
                <div class="span2" style="text-align: center">
                    <strong>item count: </strong>
                </div>
                <div class="span1" style="text-align: center">
                    <?php echo count($project->getBacklog()); ?>
                </div>
            </div>
        </div>
    </div>
</div>