<?php /** @var $this \Ctrl\View\PhpView */ ?>
<?php echo $this->pageTitle('Projects', count($this->projects)); ?>
<p></p>
<div class="btn-group">
    <?php echo $this->ctrlButton('link', array('value' => 'Add new project',
    'href' => $this->url('default', array(
        'controller' => 'project',
        'action' => 'create',
    ))), 'primary') ?>
</div>
<p></p>
<div class="">
    <table class="table table-striped">
        <tr>
            <th>id</th>
            <th>name</th>
            <th>description</th>
            <th>actions</th>
        </tr>
        <?php /** @var $p \DevCtrl\Domain\Project\Project */ ?>
        <?php foreach ($this->projects as $p): ?>
        <tr>
            <td><?php echo $p->getId(); ?></td>
            <td><?php echo $p->getName(); ?></td>
            <td><?php echo $p->getDescription(); ?></td>
            <td><a class="btn btn-info" href="<?php echo $this->url('default/id', array(
                'controller' => 'project',
                'action' => 'detail',
                'id' => $p->getId()
            )); ?>">detail</a></td>
        </tr>
        <?php endforeach; ?>
    </table>
</div>