<?php $p = $this->project /** @var $p \DevCtrl\Domain\Project */ ?>
<?php $itemTypes = $this->itemTypes /** @var $itemTypes \DevCtrl\Domain\Item\ItemType[] */ ?>
<div class="page-header"><h1><?php echo $this->project->getName(); ?></h1></div>

<?php $this->page = 'items'; ?>
<?php echo $this->render('dev-ctrl/project/partial/project-tabs.phtml'); ?>

<div class="btn-group">
    <a class="btn dropdown-toggle btn-primary" data-toggle="dropdown" href="#">
        New item
        <span class="caret"></span>
    </a>
    <ul class="dropdown-menu">
        <?php foreach ($itemTypes as $it): ?>
            <li><a href="<?php echo $this->url('item_create', array(
                'project' => $this->project->getId(),
                'item-type' => $it->getId()
            )); ?>"><?php echo $it->getName(); ?></a></li>
        <?php endforeach; ?>
    </ul>
</div>
<p></p>
<div class="">
    <table class="table table-striped">
        <tr>
            <th>id</th>
            <th>title</th>
            <th>description</th>
            <th>actions</th>
        </tr>
        <?php /** @var $p \DevCtrl\Domain\Item\Item */ ?>
        <?php foreach ($p->getItems() as $i): ?>
        <tr>
            <td><?php echo $i->getId(); ?></td>
            <td><?php echo $i->getTitle(); ?></td>
            <td><?php echo $i->getDescription(); ?></td>
            <td><a class="btn btn-info" href="<?php echo $this->url('default/id', array(
                'controller' => 'project',
                'action' => 'detail',
                'id' => $p->getId()
            )); ?>">detail</a></td>
        </tr>
        <?php endforeach; ?>
    </table>
</div>