<?php $state = $this->list; /** @var $state \DevCtrl\Domain\Item\State\StateList */ ?>

<?php $this->configTab = 'state-list'; ?>
<?php echo $this->render('dev-ctrl/partial/configuration-tabs.phtml'); ?>

<?php echo $this->pageTitle($this->list->getName(), 'State list'); ?>

<div class="btn-group">
    <?php echo $this->ctrlButton('link', array('value' => 'Add state',
    'href' => $this->url('default/id', array(
        'controller' => 'state-list',
        'action' => 'add-state',
        'id' => $state->getId(),
    ))), 'primary') ?>
    <?php echo $this->ctrlButton('link', array('value' => 'Back to index',
    'href' => $this->url('default', array(
        'controller' => 'state-list',
        'action' => 'index',
    )))) ?>
</div>

<p></p>

<table class="table table-striped">
    <tr>
        <th>id</th>
        <th>label</th>
        <th>native state</th>
        <th>order</th>
        <th>actions</th>
    </tr>
    <?php foreach ($state->getStates() as $s): ?>
    <tr>
        <td><?php echo $s->getId(); ?></td>
        <td><?php echo $s->getLabel(); ?></td>
        <td><?php echo $s->getNativeState(); ?></td>
        <td>
            <?php echo $this->orderControls('default/query', array(
                'controller' => 'state-list',
                'action' => 'change-state-order',
                'id' => $s->getList()->getId(),
                'state' => $s->getId(),
            )); ?>
        </td>
        <td>
            <?php echo $this->ctrlButton('link', array('value' => 'delete', 'confirm' => true,
            'href' => $this->url('default/id', array(
                'controller' => 'state-list',
                'action' => 'delete-state',
                'id' => $s->getId()
            ))), 'danger') ?>
        </td>
    </tr>
    <?php endforeach; ?>
</table>