<?php $this->configTab = 'state-list'; ?>
<?php echo $this->render('dev-ctrl/partial/configuration-tabs.phtml'); ?>

<?php echo $this->pageTitle('State lists'); ?>
<p></p>
<div class="btn-group">
    <?php echo $this->ctrlButton('link', array('value' => 'Add new set',
    'href' => $this->url('default', array(
        'controller' => 'state-list',
        'action' => 'create'
    ))), 'primary') ?>
</div>
<p></p>
<div class="">
    <table class="table table-striped">
        <tr>
            <th width="50">id</th>
            <th>name</th>
            <th width="100">states</th>
            <th width="100">in use</th>
            <th width="200">actions</th>
        </tr>
        <?php /** @var $l \DevCtrl\Domain\Item\State\StateList */ ?>
        <?php foreach ($this->lists as $l): ?>
        <tr>
            <td><?php echo $l->getId(); ?></td>
            <td><?php echo $l->getName(); ?></td>
            <td><?php echo count($l->getStates()); ?></td>
            <td><?php echo count($l->getItemTypes()) ? 'yes': 'no'; ?></td>
            <td>
                <?php echo $this->ctrlButton('link', array('value' => 'detail',
                'href' => $this->url('default/id', array(
                    'controller' => 'state-list',
                    'action' => 'detail',
                    'id' => $l->getId()
                ))), 'info') ?>
                <?php if(!count($l->getItemTypes())): ?>
                <?php echo $this->ctrlButton('link', array('value' => 'delete', 'confirm' => true,
                    'href' => $this->url('default/id', array(
                        'controller' => 'state-list',
                        'action' => 'delete',
                        'id' => $l->getId()
                    ))), 'danger') ?>
                <?php endif; ?>
            </td>
        </tr>
        <?php endforeach; ?>
    </table>
</div>