<?php echo $this->doctype(); ?>

<html lang="en">
    <head>
        <meta charset="utf-8">
        <?php echo $this->headTitle('ZF2 '. $this->translate('Skeleton Application'))->setSeparator(' - ')->setAutoEscape(false) ?>

        <?php echo $this->headMeta()->appendName('viewport', 'width=device-width, initial-scale=1.0') ?>

        <!-- Le styles -->
        <?php echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/images/favicon.ico'))
                        ->appendStylesheet($this->basePath() . '/css/bootstrap.css')
                        ->appendStylesheet($this->basePath() . '/css/bootstrap-responsive.min.css')
                        ->appendStylesheet($this->basePath() . '/modules/dev-ctrl/css/style.css') ?>

        <!-- vendor scripts -->
        <?php
            echo $this->ctrlJsLoader()->loadScripts(true);
        ?>
        <!-- Custom Scripts -->
        <?php //echo $this->headScript()->appendFile($this->basePath() . '/js/ctrljs.config.js'); ?>
  </head>
  <body>

    <div class="navbar navbar-fixed-top">
      <div class="navbar-inner">
        <div class="container">
          <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">

            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </a>
            <a class="brand" href="<?php echo $this->url('home') ?>"><?php echo $this->translate('Dev Ctrl') ?></a>
          <div class="nav-collapse">
            <ul class="nav">
                <li class="active"><a href="<?php echo $this->url('home') ?>"><?php echo $this->translate('Home') ?></a></li>
                <li class="active"><a href="<?php echo $this->url('default', array(
                    'controller' => 'item-type',
                )) ?>"><?php echo $this->translate('Configuration') ?></a></li>
            </ul>
          </div><!--/.nav-collapse -->
        </div>
      </div>
    </div>

    <div class="container">

      <?php echo $this->content; ?>

      <hr>

      <footer>
        <p>&copy; 0.0.0 development</p>
      </footer>

    </div> <!-- /container -->

  </body>
</html>
