<?php use DevCtrl\Domain\Item\Property\Property; ?>
<?php $itemType = $this->itemType; /** @var $itemType \DevCtrl\Domain\Item\Type\Type */ ?>
<h1>New property
    <small>for <strong><?php echo $itemType->getName(); ?></strong></small>
</h1>

<form class="form-horizontal" method="post" id="item-type-state-form" action="<?php echo $this->url('default/id', array(
    'controller' => 'item-type',
    'action' => 'create-state',
    'id' => $itemType->getId(),
)); ?>">
    <fieldset>
        <legend>Configure your property</legend>
        <div class="control-group">
            <label class="control-label">name</label>
            <div class="controls">
                <input type="text" class="input-xxlarge required" name="name" />
            </div>
        </div>
        <div class="control-group">
            <label class="control-label">description</label>
            <div class="controls">
                <input type="text" class="input-xxlarge" name="name" />
            </div>
        </div>
        <div class="control-group">
            <label class="control-label">type</label>
            <div class="controls">
                <select class="input-large required" name="type">
                    <option value="<?php echo Property::TYPE_SINGLE; ?>">text</option>
                    <option value="<?php echo Property::TYPE_BOOL; ?>">boolean</option>
                    <option value="<?php echo Property::TYPE_LIST; ?>">list</option>
                </select>
            </div>
        </div>
        <div class="control-group">
            <label class="control-label">static default</label>
            <div class="controls">
                <input type="text" class="input-xxlarge" name="static-default" />
            </div>
        </div>
        <div class="control-group">
            <label class="control-label">default value provider</label>
            <div class="controls">
                <select class="input-large required" name="default-value-provider">
                    <?php foreach ($this->defaultValueProviders as $p): ?>
                        <option><?php echo $p; ?></option>
                    <?PHP endforeach; ?>
                </select>
            </div>
        </div>
        <div class="control-group">
            <label class="control-label">possible values provider</label>
            <div class="controls">
                <select class="input-large required" name="possible-values-provider">
                    <?php foreach ($this->possibleValuesProviders as $p): ?>
                    <option><?php echo $p; ?></option>
                    <?PHP endforeach; ?>
                </select>
            </div>
        </div>
        <div class="form-actions">
            <input type="submit" class="btn btn-primary" value="save">
            <a class="btn" href="<?php echo $this->url('default/id', array(
                'controller' => 'item-type',
                'action' => 'states',
                'id' => $itemType->getId(),
            )); ?>">cancel</a>
        </div>
    </fieldset>

</form>


<script type="text/javascript">
    $(function () {
        $('form#item-type-state-form').live('submit', function () {
            if (Ctrl.forms().isValid($(this))) {
                $('form#item-form .form-actions .alert').remove();
            } else {
                $('form#item-form .form-actions').prepend(
                    $('<div class="alert alert-error"><strong>Hold on!</strong> Some required fields are missing a value.</div>')
                );
                return false;
            }
            return true;
        });
    });
</script>