<?php use DevCtrl\Domain\Item\Type\Type; ?>
<?php $type = $this->itemType; /** @var $type Type */ ?>
<div class="page-header"><h1>Item Type <small><?php echo $this->itemType->getName(); ?></small></h1></div>

<?php $this->page = 'info'; ?>
<?php echo $this->render('dev-ctrl/item-type/partial/item-type-tabs.phtml'); ?>

<table class="table table-bordered">
    <tr>
        <th>name</th>
        <td colspan=""><?php echo $this->itemType  ->getName(); ?></td>
        <th>supports timing</th>
        <td><?php echo $type->supportsTiming() ? 'yes' : 'no' ?></td>
    </tr>
    <tr>
        <th>description</th>
        <td colspan="3"><?php echo $this->itemType->getDescription(); ?></td>
    </tr>
    <tr>
        <th>has state</th>
        <td><?php echo $type->hasStates() ? 'yes' : 'no' ?></td>
        <th>state set</th>
        <td><?php if ($type->hasStates()) $type->getStates()->getName() ?></td>
    </tr>
</table>