<div class="page-header" xmlns="http://www.w3.org/1999/html"><h1>Item Type <small><?php echo $this->itemType->getName(); ?></small></h1></div>

<?php $this->page = 'info'; ?>
<?php echo $this->render('dev-ctrl/item-type/partial/item-type-tabs.phtml'); ?>

<table class="table table-bordered">
    <tr>
        <th>name</th>
        <td colspan="3"><?php echo $this->itemType->getName(); ?></td>
    </tr>
    <tr>
        <th>description</th>
        <td colspan="3"><?php echo $this->itemType->getDescription(); ?></td>
    </tr>
    <tr>
        <th>is timed</th>
        <td><?php echo $this->itemType->supportsTiming() ? 'yes' : 'no' ?></td>
        <th>has state</th>
        <td><?php echo $this->itemType->supportsStates() ? 'yes' : 'no' ?></td>
    </tr>
</table>