<?php $this->configTab = 'item-type'; ?>
<?php echo $this->render('dev-ctrl/partial/configuration-tabs.phtml'); ?>

<?php echo $this->pageTitle('Item types'); ?>
<div class="btn-group">
    <?php echo $this->ctrlButton('link', array('value' => 'Add new type',
    'href' => $this->url('default', array(
        'controller' => 'item-type',
        'action' => 'create'
    ))), 'primary') ?>
</div>
<p></p>
<div class="">
    <table class="table table-striped">
        <tr>
            <th>id</th>
            <th>name</th>
            <th>description</th>
            <th>supports timing</th>
            <th>states set</th>
            <th>actions</th>
        </tr>
        <?php /** @var $p \DevCtrl\Domain\Item\Type\Type */ ?>
        <?php foreach ($this->itemTypes as $p): ?>
        <tr>
            <td><?php echo $p->getId(); ?></td>
            <td><?php echo $p->getName(); ?></td>
            <td><?php echo $p->getDescription(); ?></td>
            <td><?php echo $p->supportsTiming() ?></td>
            <td><?php echo $p->hasStates() ? $p->getStates()->getName() : ''; ?></td>
            <td>
                <?php echo $this->ctrlButton('link', array('value' => 'detail',
                'href' => $this->url('default/id', array(
                    'controller' => 'item-type',
                    'action' => 'detail',
                    'id' => $p->getId()
                ))), 'info') ?>
        </tr>
        <?php endforeach; ?>
    </table>
</div>