<h1>Item Types</h1>

<div class="">
    <table class="table table-striped">
        <tr>
            <th>id</th>
            <th>name</th>
            <th>description</th>
            <th>timed</th>
            <th>has states</th>
            <th>actions</th>
        </tr>
        <?php /** @var $p \DevCtrl\Domain\Item\ItemType */ ?>
        <?php foreach ($this->itemTypes as $p): ?>
        <tr>
            <td><?php echo $p->getId(); ?></td>
            <td><?php echo $p->getName(); ?></td>
            <td><?php echo $p->getDescription(); ?></td>
            <td><?php echo $p->getTimed() ?></td>
            <td><?php echo $p->getHasState(); ?></td>
            <td><a class="btn btn-info" href="<?php echo $this->url('default/id', array(
                'controller' => 'item-type',
                'action' => 'detail',
                'id' => $p->getId()
            )); ?>">detail</a></td>
        </tr>
        <?php endforeach; ?>
    </table>
</div>