<?php $itemType = $this->itemType /** @var $itemType \DevCtrl\Domain\Item\Type\Type */ ?>

<?php $this->configTab = 'property'; ?>
<?php echo $this->render('dev-ctrl/partial/configuration-tabs.phtml'); ?>

<?php echo $this->pageTitle('Item type', $this->itemType->getName()); ?>

<?php $this->page = 'properties'; ?>
<?php echo $this->render('dev-ctrl/item-type/partial/item-type-tabs.phtml'); ?>

<div class="btn-group">
    <a class="btn btn-primary" data-toggle="dropdown" href="<?php echo $this->url('default/id', array(
        'controller' => 'item-type',
        'action' => 'select-link-property',
        'id' => $itemType->getId(),
    )); ?>">Add property</a>
</div>
<p></p>
<div>
    <table class="table table-striped">
        <tr>
            <th>id</th>
            <th>name</th>
            <th>required</th>
            <th>default value</th>
            <th>change order</th>
            <th>actions</th>
        </tr>
        <?php foreach ($itemType->getTypeProperties() as $itp): ?>
        <tr>
            <td><?php echo $itp->getId(); ?></td>
            <td><?php echo $itp->getProperty()->getName(); ?></td>
            <td><?php echo $itp->getRequired() ? 'yes' : 'no' ?></td>
            <td><?php if ($itp->getProperty()->getType()->supportsDefaultValue()) echo $itp->getDefaultProvider()->getName() ?></td>
            <td>
                <?php echo $this->orderControls('default/id/query', array(
                    'controller' => 'item-type',
                    'action' => 'change-property-order',
                    'id' => $itp->getId(),
                )); ?>
            </td>
            <td>
                <?php echo $this->ctrlButton('link', array('value' => 'edit',
                'href' => $this->url('default/id', array(
                    'controller' => 'item-type',
                    'action' => 'edit',
                    'id' => $itp->getId()
                ))), 'primary') ?>
                <?php echo $this->ctrlButton('link', array('value' => 'delete', 'confirm' => true,
                'href' => $this->url('default/id', array(
                    'controller' => 'item-type',
                    'action' => 'delete-property',
                    'id' => $itp->getId()
                ))), 'danger') ?>
            </td>
        </tr>
        <?php endforeach; ?>
    </table>
</div>