<?php
echo $this->pageTitle('Link to item type', $this->itemType->getName());
echo $this->pageTitle('Select the property you want to link', null, array('level' => 3));
?>
<p></p>
<div class="btn-group">
    <?php echo $this->ctrlButton('link', array('value' => 'Back to index',
    'href' => $this->url('default/id', array(
        'controller' => 'item-type',
        'action' => 'properties',
        'id' => $this->itemType->getId(),
    )))) ?>
</div>
<p></p>
<div class="">
    <table class="table table-striped">
        <tr>
            <th>name</th>
            <th>description</th>
            <th>actions</th>
        </tr>
        <?php /** @var $p \DevCtrl\Domain\Item\Property\Property */ ?>
        <?php foreach ($this->properties as $p): ?>
        <tr>
            <td><?php echo $p->getName(); ?></td>
            <td><?php echo $p->getDescription(); ?></td>
            <td>
                <?php echo $this->ctrlButton('link', array('value' => 'add',
                'href' => $this->url('type_property_link', array(
                    'type' => $this->itemType->getId(),
                    'property' => $p->getId(),
                ))), 'primary') ?>
            </td>
        </tr>
        <?php endforeach; ?>
    </table>
</div>