<h1>Link property to item type</h1>
<p></p>
<h4>Select the property you would like to link</h4>
<p></p>
<div class="">
    <table class="table table-striped">
        <tr>
            <th>name</th>
            <th>description</th>
            <th>actions</th>
        </tr>
        <?php /** @var $p \DevCtrl\Domain\Item\Property\Property */ ?>
        <?php foreach ($this->properties as $p): ?>
        <tr>
            <td><?php echo $p->getName(); ?></td>
            <td><?php echo $p->getDescription(); ?></td>
            <td><a class="btn btn-primary" href="<?php echo $this->url('type_property_link', array(
                'type' => $this->itemType->getId(),
                'property' => $p->getId(),
            )); ?>">link</a></td>
        </tr>
        <?php endforeach; ?>
    </table>
</div>