<?php $itemType = $this->itemType /** @var $itemType \DevCtrl\Domain\Item\Type\Type */ ?>

<?php $this->configTab = 'property'; ?>
<?php echo $this->render('dev-ctrl/partial/configuration-tabs.phtml'); ?>

<?php echo $this->pageTitle('Item type', $itemType->getName()); ?>

<?php $this->page = 'states'; ?>
<?php echo $this->render('dev-ctrl/item-type/partial/item-type-tabs.phtml'); ?>

<?php if ($itemType->supportsStates()): ?>
<div class="btn-group">
    <a class="btn" data-toggle="dropdown" href="<?php echo $this->url('default/id', array(
        'controller' => 'state-list',
        'action' => 'detail',
        'id' => $itemType->getStates()->getId(),
    )); ?>">state list configuration</a>
</div>
<p></p>
<div class="">
    <table class="table table-striped">
        <tr>
            <th>order</th>
            <th>name</th>
            <th>type</th>
        </tr>
        <?php foreach ($itemType->getStates()->getStates() as $s): ?>
        <tr>
            <td><?php echo $s->getOrder(); ?></td>
            <td><?php echo $s->getLabel(); ?></td>
            <td><?php echo $s->getNativeState(); ?></td>
        </tr>
        <?php endforeach; ?>
    </table>
</div>
<?php endif; ?>