<?php $list = $this->list; /** @var $list \DevCtrl\Domain\Item\Property\Value\ValueList */ ?>
<?php $nativeType = $this->nativeType; /** @var $nativeType \DevCtrl\Domain\Item\Property\Value\NativeValueInterface */ ?>
<h1>Add a value</small>
</h1>

<form class="form-horizontal" method="post" id="item-form" action="<?php echo $this->url('default/id', array(
    'controller' => 'value-list',
    'action' => 'add-value',
    'id' => $list->getId(),
)); ?>">
    <fieldset class="part-1">
        <legend>Configure your item</legend>
        <div class="control-group">
            <label class="control-label">value</label>
            <div class="controls">
                <?php switch ($list->getNativeType()):
                    case 'string':
                    case 'integer': ?>
                        <input type="text" class="input-xxlarge required" name="value" />
                        <?php break; ?>
                <?php
                    case 'boolean': ?>
                        <input type="checkbox" name="value" />
                        <?php break; ?>
                <?php endswitch; ?>
            </div>
        </div>
        <div class="form-actions">
            <input type="submit" class="btn btn-primary" value="save" />
            <a class="btn" href="<?php echo $this->url('default/id', array(
                'controller' => 'value-list',
                'action' => 'detail',
                'id' => $list->getId(),
            )); ?>">cancel</a>
        </div>
    </fieldset>
</form>