<?php $list = $this->list; /** @var $list \DevCtrl\Domain\Item\Property\Value\ValueList */ ?>

<?php $this->configTab = 'value-list'; ?>
<?php echo $this->render('dev-ctrl/partial/configuration-tabs.phtml'); ?>

<?php echo $this->pageTitle($list->getName(), 'Custom list'); ?>

<div class="btn-group">
    <?php echo $this->ctrlButton('link', array('value' => 'Add value',
    'href' => $this->url('default/id', array(
        'controller' => 'value-list',
        'action' => 'add-value',
        'id' => $list->getId(),
    ))), 'primary') ?>
    <?php echo $this->ctrlButton('link', array('value' => 'Back to index',
    'href' => $this->url('default', array(
        'controller' => 'value-list',
        'action' => 'index',
    )))) ?>
</div>
<p></p>
<div class="">
    <table class="table table-striped">
        <tr>
            <th width="50">order</th>
            <th>value</th>
            <th width="200">actions</th>
        </tr>
        <?php foreach ($list->getValues() as $v): ?>
        <tr>
            <td><?php echo $v->getOrder(); ?></td>
            <td><?php echo $v->getValue()->getValue(); ?></td>
            <td>
                <?php echo $this->orderControls('default/id/query', array(
                    'controller' => 'value-list',
                    'action' => 'change-value-order',
                    'id' => $v->getId(),
                )); ?>
                <?php echo $this->ctrlButton('link', array('value' => 'delete', 'confirm' => true,
                'href' => $this->url('default/id', array(
                    'controller' => 'value-list',
                    'action' => 'delete-value',
                    'id' => $v->getId()
                ))), 'danger') ?>
            </td>
        </tr>
        <?php endforeach; ?>
    </table>
</div>