<?php $list = $this->list; /** @var $list \DevCtrl\Domain\Item\Property\Value\ValueList */ ?>
<div class="page-header"><h1>Value list <small><?php echo $this->list->getName(); ?></small></h1></div>

<div class="btn-group">
    <a class="btn btn-primary" data-toggle="dropdown" href="<?php echo $this->url('default/id', array(
        'controller' => 'value-list',
        'action' => 'add-value',
        'id' => $list->getId(),
    )); ?>">Add value</a>
</div>
<p></p>
<div class="">
    <table class="table table-striped">
        <tr>
            <th>id</th>
            <th>value</th>
            <th>actions</th>
        </tr>
        <?php foreach ($list->getValues() as $v): ?>
        <tr>
            <td><?php echo $v->getId(); ?></td>
            <td><?php echo $v->getValue(); ?></td>
            <td><a class="btn btn-danger" href="<?php echo $this->url('default/id', array(
                'controller' => 'value-list',
                'action' => 'detail',
                'id' => $v->getId()
            )); ?>">delete</a></td>
        </tr>
        <?php endforeach; ?>
    </table>
</div>