<?php $this->configTab = 'value-list'; ?>
<?php echo $this->render('dev-ctrl/partial/configuration-tabs.phtml'); ?>

<?php echo $this->pageTitle('Custom lists'); ?>
<p></p>
<div class="btn-group">
    <a class="btn dropdown-toggle btn-primary" data-toggle="dropdown" href="#">
        New custom list
        <span class="caret"></span>
    </a>
    <ul class="dropdown-menu">
        <?php foreach ($this->nativeTypes as $id => $t): ?>
        <li><a href="<?php echo $this->url('value_list_create', array(
            'type' => $id
        )); ?>"><?php echo $t['name']; ?></a></li>
        <?php endforeach; ?>
    </ul>
</div>
<p></p>
<div class="">
    <table class="table table-striped">
        <tr>
            <th>id</th>
            <th>name</th>
            <th>value type</th>
            <th>values</th>
            <th>actions</th>
        </tr>
        <?php /** @var $l \DevCtrl\Domain\Item\Property\Value\ValueList */ ?>
        <?php foreach ($this->lists as $l): ?>
        <tr>
            <td><?php echo $l->getId(); ?></td>
            <td><?php echo $l->getName(); ?></td>
            <td><?php echo $l->getNativeType(); ?></td>
            <td><?php echo count($l->getValues()) ?></td>
            <td>
                <?php echo $this->ctrlButton('link', array(
                'value' => 'detail',
                'href' => $this->url('default/id', array(
                    'controller' => 'value-list',
                    'action' => 'detail',
                    'id' => $l->getId()
                ))), 'info') ?>
                <?php if(!count($l->getValues())): ?>
                <?php echo $this->ctrlButton('link', array(
                    'value' => 'delete',
                    'confirm' => true,
                    'href' => $this->url('default/id', array(
                        'controller' => 'state-list',
                        'action' => 'delete',
                        'id' => $l->getId()
                    ))), 'danger') ?>
                <?php endif; ?>
        </tr>
        <?php endforeach; ?>
    </table>
</div>