<?php $i = $item; ?>
<?php $detailUrl = $this->url('default/id', array('controller' => 'item', 'action' => 'detail', 'id' => $i->getId())); ?>
<div class="container-fluid well devctrl-item-widget devctrl-item-widget-row" data-widget-item-id="<?php echo $i->getProgress(); ?>" style="padding: 5px;">
    <div class="row-fluid">
        <div class="span1">
            <canvas class="ctrljs-3stage-gauge" guage-value="<?php echo $i->getProgress(); ?>" width="50" height="50"></canvas>
        </div>
        <div class="span11">
            <div class="row-fluid">
                <div class="span1">
                    <a href="<?php echo $detailUrl; ?>">
                        #<?php echo $i->getId(); ?>
                    </a>
                </div>
                <div class="span7">
                    <div class="btn-group">
                        <a class="btn dropdown-toggle" data-toggle="dropdown" href="#">
                            <?php echo $i->getTitle(); ?>
                            <span class="caret"></span>
                        </a>
                        <ul class="dropdown-menu">
                            <li><a href="<?php echo $detailUrl; ?>">detail</a></li>
                            <li><a href="<?php echo $this->url('default/id', array('controller' => 'item', 'action' => 'edit', 'id' => $i->getId())); ?>">edit</a></li>
                            <li><a href="<?php echo $detailUrl; ?>">assign to me</a></li>
                        </ul>
                    </div>
                </div>
                <div class="span1">
                    <?php if ($i->getVersionReported()):?><strong>reported</strong><?php endif; ?>
                </div>
                <div class="span1">
                    <?php if ($i->getVersionReported()) echo $i->getVersionReported()->getVersion(); ?>
                </div>
                <div class="span2">
                    <?php
                    if ($i->getItemType()->supportsTiming())
                        echo '<span class="icon-time"></span> '.
                            $i->getTimeCounter()->getExecuted().' / '.
                            $i->getTimeCounter()->getEstimated()
                    ?>
                </div>
            </div>
            <div class="row-fluid">
                <div class="span1">
                    <?php if ($i->getItemType()->supportsStates()): ?>
                    <span class="label label-<?php
                        echo ($i->getState()->getNativeState() == $i->getState()->getNativeStates(\DevCtrl\Domain\Item\State\State::STATE_CLOSED)) ?
                            'inverse': 'success'; ?>"><?php echo $i->getState()->getLabel() ?></span>
                    <?php endif; ?>
                </div>
                <div class="span7">
                    <?php echo $i->getDescription(); ?>
                </div>
                <div class="span1">
                    <?php if ($i->getVersionFixed()):?><strong>fixed</strong><?php endif; ?>
                </div>
                <div class="span1">
                    <?php if ($i->getVersionFixed()) echo $i->getVersionFixed()->getVersion(); ?>
                </div>
                <div class="span2">
                    <?php echo $this->formatDate($i->getDateCreated(), 'Y-m-d'); ?>
                </div>
            </div>
        </div>
    </div>
</div>